### ISSUE TITLE
no frame when bMemoryMode==true

### ISSUE THREAD

**Issue by phields** [leadedge/SpoutCam#1]

**Comment by leadedge** [comment]
The latest version is based on DirectX and memoryshare has not been implemented yet. The original version, based on OpenGL, can now be found in the OpenGL branch and this supports memoryshare. The code is different and cannot be exchanged. Updates to the DirectX version will not be carried over and the OpenGL version may eventually be discontinued.

You only need to exchange two files, SpoutCam32.ax and SpoutCam64.ax in the releases folder. The easiest way to change is to use "_reregister_run_as_admin.bat". RH click and "Run as administrator".
