### ISSUE TITLE
The color is not displayed correctly.

### ISSUE THREAD

**Issue by qq357075581** [leadedge/SpoutCam#11]
Hello author. I am using the KlakSpout plugin, and I want to display Unity content through SpoutCam. However, the colors displayed in SpoutCam do not match the colors shown in Unity. I don't know what the problem is. I saw there is a Swap option in SpoutCam Settings, but switching it doesn't have any effect.
![微信截图_20240519015935](https://github.com/leadedge/SpoutCam/assets/26922978/ca235c97-1fd9-435d-828c-0cdd30f0a7df)
![微信截图_20240519015904](https://github.com/leadedge/SpoutCam/assets/26922978/2aa9bd05-cc82-4e2f-924c-27bbad3f647e)

**Comment by leadedge** [comment]
The swap effect takes effect when SpoutCam is loaded, so make sure that swap is enabled before you start the host program using SpoutCam. After it is loaded, changes in the settings have no effect until it is loaded again.

**Comment by qq357075581** [comment]
I have tried many methods, but none of them work. I am using the KlakSpout template project and Unity's default rendering pipeline. First, I register using SpoutCamSettings.exe, then open OBS and activate SpoutCam. After that, I open Unity and run it (during this process, SpoutCam needs to be activated again to receive the image). The displayed result is still incorrect (I have tried the same process with the Swap option both enabled and disabled).
![微信截图_20240519145532](https://github.com/leadedge/SpoutCam/assets/26922978/d5de2342-f6ef-49c8-89d8-bde49229cad9)
![微信截图_20240519145549](https://github.com/leadedge/SpoutCam/assets/26922978/c6c1c8c1-7271-404e-8840-1add2ed6c579)

**Comment by leadedge** [comment]
I am not sure why you are using SpoutCam in OBS. There is a  Spout fillter for OBS by [Off World Live](https://github.com/Off-World-Live/obs-spout2-plugin/releases). This will receive from Unity directly at much higher speed.

The OBS "Video Capture Device" filter with SpoutCam selected also has a "Configure Video" button in the settings which allows "Swap" to be changed. After the saving change, the filter is re-set and SpoutCam uses the new settings. "Deactivate/Activate" can also be used.

**Comment by qq357075581** [comment]
Hello, author. I encountered the current issue with versions 2.029-2.031, but the display works correctly with version 2.027 and below. Could it be that the KlakSpout version is too old?Thank you for your reply.

**Comment by leadedge** [comment]
Yes there could have been a change. I see that the current version of KlakSpout creates a shared texture of RGBA format, previous versions could have been BGRA. It's only a problem for SpoutCam which can't adapt automatically to different formats.

**Comment by leadedge** [comment]
FYI. I have found a solution for SpoutCam. There is a litttle more to do yet but I will make a new release when it is ready.

**Comment by qq357075581** [comment]
Thank you very much! : )
