### ISSUE TITLE
rgba support

### ISSUE THREAD

**Issue by phields** [leadedge/SpoutCam#3]
I noticed that the code converts RGBA shared texture to RGB.
There seems to be alpha channel support in other virtual camera projects
https://github.com/schellingb/UnityCapture
I'm not sure if this is a compatibility concern, but it is possible in OBS studio to get the transparency of the virtual camera source.

**Comment by leadedge** [comment]
The filter is based on quite old code and is set up for an incoming stream of RGB format. You will find that in Cam.cpp "CVCamStream::GetStreamCaps". I might be possible to set it up as RGBA but it really needs a DirectShow expert to investigate that and I would not like to tackle it.

**Comment by leadedge** [comment]
I think I have to close this because it's not something I can do with the old code it's based on. If somebody with DirectShow skills gets inspired, I will assist.
