### ISSUE TITLE
Black screen using Spout Sender Demo and OBS/GoogleMeet

### ISSUE THREAD

**Issue by rtizzy** [leadedge/SpoutCam#8]
So I have no idea what I did but I managed to get things working briefly then was completely unable to replicate it. Right now I simply get a black screen. 

Here is how my issue can be reproduced:

1. Ensure the latest version of Spout is installed.
3. Download the latest version v2.030 of Spoutcam, open the application and register.
4. Leave all other settings at the defaults and click OK. 
5. Start the Spout Sender Demo.
6. Attempt to use SpoutCam virtual camera in OBS or Google Meet. 
7. It does not work, just a black screen. 

As I mentioned I was at some point able to get this working momentarily with NestDropMidnight and OBS but then was unable to get it working again. 

Any help would be appreciate and can help troubleshoot.

**Comment by leadedge** [comment]
If Spoutcam is detected but is not receiving you should get a static noise image. Try running a Spout sender before opening SpoutCam in OBS etc. Try an online webcam test. [This one](https://webcamtests.com/) seems to work.

**Comment by leadedge** [comment]
I will close this now. Please comment again if you have not solved this.
