### ISSUE TITLE
specify another name for the output camera

### ISSUE THREAD

**Issue by Alberthalbautomaten** [leadedge/SpoutCam#9]
Any chance you could enable that? Like executing the .bat files with a parameter like this? 

`_register_run_as_admin.bat - "CamName"`

Or is this already possible?

**Comment by leadedge** [comment]
This is not possible without creating another filter. The SpoutCam code would have to be changed to use another name for the filter. Then that would be registered under the different name. The name is also connected to a CLSID which might also need to be changed. So it isn't a straightforward process.
